version: '3'
services:
    db:
        image: postgres:10.4
        environment:
            POSTGRES_PASSWORD: enviu_dev
            POSTGRES_USER: postgres          
    blockscout:
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./../:/home/blockscout/src
        ports:
            - "4000:4000"
        tty: true